-- MySQL Script generated by MySQL Workbench
-- ven. 25 nov. 2016 16:25:01 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema DDCSPP
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DDCSPP
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DDCSPP` DEFAULT CHARACTER SET utf8 ;
USE `DDCSPP` ;

-- -----------------------------------------------------
-- Table `DDCSPP`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DDCSPP`.`role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `gestion_block` TINYINT(1) NULL,
  `gestion_user` TINYINT(1) NULL,
  `gestion_them` TINYINT(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DDCSPP`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DDCSPP`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pseudo` VARCHAR(45) NULL,
  `mail` VARCHAR(45) NULL,
  `pwd` VARCHAR(45) NULL,
  `salt` VARCHAR(45) NULL,
  `role` VARCHAR(45) NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_role1_idx` (`role_id` ASC),
  CONSTRAINT `fk_user_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `DDCSPP`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DDCSPP`.`media`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DDCSPP`.`media` (
  `id_media` INT NOT NULL AUTO_INCREMENT,
  `type_media` VARCHAR(45) NULL,
  `url` VARCHAR(45) NULL,
  `poste_id` INT NOT NULL,
  PRIMARY KEY (`id_media`),
  INDEX `fk_media_poste1_idx` (`poste_id` ASC),
  CONSTRAINT `fk_media_poste1`
    FOREIGN KEY (`poste_id`)
    REFERENCES `DDCSPP`.`post` (`id_poste`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DDCSPP`.`poste`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DDCSPP`.`poste` (
  `id_poste` INT NOT NULL AUTO_INCREMENT,
  `auteur` INT NULL,
  `date` DATE NULL,
  `titre` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `user_id` INT NOT NULL,
  `media_id_media` INT NOT NULL,
  PRIMARY KEY (`id_poste`, `user_id`, `media_id_media`),
  INDEX `fk_poste_user_idx` (`user_id` ASC),
  INDEX `fk_poste_media1_idx` (`media_id_media` ASC),
  CONSTRAINT `fk_poste_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `DDCSPP`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_poste_media1`
    FOREIGN KEY (`media_id_media`)
    REFERENCES `DDCSPP`.`media` (`id_media`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DDCSPP`.`them`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DDCSPP`.`them` (
  `id_them` INT NOT NULL,
  `color` VARCHAR(45) NULL,
  `opacity` VARCHAR(45) NULL,
  `image` MEDIUMBLOB NULL,
  `repeat` TINYINT(1) NULL,
  `parallax` TINYINT(1) NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id_them`, `user_id`),
  INDEX `fk_them_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_them_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `DDCSPP`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DDCSPP`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DDCSPP`.`post` (
  `id_poste` INT NOT NULL,
  `titre` VARCHAR(45) NULL,
  `date` DATE NULL,
  `description` VARCHAR(500) NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id_poste`),
  INDEX `fk_poste_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_poste_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `DDCSPP`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DDCSPP`.`media`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DDCSPP`.`media` (
  `id_media` INT NOT NULL AUTO_INCREMENT,
  `type_media` VARCHAR(45) NULL,
  `url` VARCHAR(45) NULL,
  `poste_id` INT NOT NULL,
  PRIMARY KEY (`id_media`),
  INDEX `fk_media_poste1_idx` (`poste_id` ASC),
  CONSTRAINT `fk_media_poste1`
    FOREIGN KEY (`poste_id`)
    REFERENCES `DDCSPP`.`post` (`id_poste`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DDCSPP`.`theme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DDCSPP`.`theme` (
  `id` INT NULL AUTO_INCREMENT,
  `color` VARCHAR(45) NULL,
  `opacity` INT NULL,
  `image` VARCHAR(45) NULL,
  `bg_repeat` TINYINT(1) NULL,
  `bg_parallax` TINYINT(1) NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
